language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script: "rake spec"
branches:
  only:
    - stage_boss
env:
  - PUPPET_VERSION=2.6.1
  - PUPPET_VERSION=2.7.1
  - PUPPET_VERSION=2.7.20
  - PUPPET_VERSION=3.1.0
matrix:
  allow_failures:
      - env: PUPPET_VERSION=2.7.1
      - env: PUPPET_VERSION=2.6.1
