language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
script: "rake spec"
branches:
  only:
    - stage_boss
env:
  - PUPPET_VERSION=2.7.1
  - PUPPET_VERSION=2.7.20
  - PUPPET_VERSION=3.0.2
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.14
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.14
  allow_failures:
    - rvm: 1.8.7
      env: PUPPET_VERSION=2.6.14
